"""add_contract_type_to_fut_contracts

Revision ID: 00da0b5a5a4a
Revises: aa66a16f977d
Create Date: 2026-05-06 22:41:18.781016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00da0b5a5a4a'
down_revision: Union[str, None] = 'aa66a16f977d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fut_contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_type', sa.String(length=10), nullable=True))
        batch_op.create_index(batch_op.f('ix_fut_contracts_contract_type'), ['contract_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fut_contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fut_contracts_contract_type'))
        batch_op.drop_column('contract_type')

    # ### end Alembic commands ###
