"""migrate remaining price fields from float to numeric

Revision ID: 1120a1ca174c
Revises: 4d8abe1e048a
Create Date: 2026-05-20 20:56:36.123456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1120a1ca174c'
down_revision: Union[str, None] = '4d8abe1e048a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fut_contracts', schema=None) as batch_op:
        batch_op.alter_column('multiplier',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('per_unit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('fut_index', schema=None) as batch_op:
        batch_op.alter_column('close',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('open_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('high',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('low',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('pre_close',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('change',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('pct_chg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('vol',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('fut_price_limits', schema=None) as batch_op:
        batch_op.alter_column('up_limit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('down_limit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('m_ratio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('fut_settle', schema=None) as batch_op:
        batch_op.alter_column('trading_fee_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('trading_fee',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('delivery_fee',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('b_hedging_margin_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('s_hedging_margin_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('long_margin_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('short_margin_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('offset_today_fee',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('fut_trade_fee', schema=None) as batch_op:
        batch_op.alter_column('current_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('up_limit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('down_limit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('margin_buy_open',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('margin_sell_open',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('fee_open_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=6),
               existing_nullable=True)
        batch_op.alter_column('fee_close_yesterday_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=6),
               existing_nullable=True)
        batch_op.alter_column('fee_close_today_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=6),
               existing_nullable=True)
        batch_op.alter_column('fee_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('tick_profit_net',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('fut_weekly_detail', schema=None) as batch_op:
        batch_op.alter_column('vol',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('vol_yoy',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('amout_yoy',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('cumvol',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('cumvol_yoy',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('cumamt',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('cumamt_yoy',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('open_interest',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('interest_wow',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('mc_close',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('close_wow',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('varieties', schema=None) as batch_op:
        batch_op.alter_column('tick_size',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('multiplier',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('varieties', schema=None) as batch_op:
        batch_op.alter_column('multiplier',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('tick_size',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    with op.batch_alter_table('fut_weekly_detail', schema=None) as batch_op:
        batch_op.alter_column('close_wow',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('mc_close',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('interest_wow',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('open_interest',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('cumamt_yoy',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('cumamt',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('cumvol_yoy',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('cumvol',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('amout_yoy',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('vol_yoy',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('vol',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    with op.batch_alter_table('fut_trade_fee', schema=None) as batch_op:
        batch_op.alter_column('tick_profit_net',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('fee_total',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('fee_close_today_rate',
               existing_type=sa.Numeric(precision=19, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('fee_close_yesterday_rate',
               existing_type=sa.Numeric(precision=19, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('fee_open_rate',
               existing_type=sa.Numeric(precision=19, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('margin_sell_open',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('margin_buy_open',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('down_limit',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('up_limit',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('current_price',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    with op.batch_alter_table('fut_settle', schema=None) as batch_op:
        batch_op.alter_column('offset_today_fee',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('short_margin_rate',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('long_margin_rate',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('s_hedging_margin_rate',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('b_hedging_margin_rate',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('delivery_fee',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('trading_fee',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('trading_fee_rate',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    with op.batch_alter_table('fut_price_limits', schema=None) as batch_op:
        batch_op.alter_column('m_ratio',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('down_limit',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('up_limit',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    with op.batch_alter_table('fut_index', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('vol',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('pct_chg',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('change',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('pre_close',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('low',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('high',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('open_price',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('close',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    with op.batch_alter_table('fut_contracts', schema=None) as batch_op:
        batch_op.alter_column('per_unit',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('multiplier',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    # ### end Alembic commands ###
