"""drop_comment_product_fk_make_variety_required

Revision ID: 21238bb1117f
Revises: 36075c47fab3
Create Date: 2026-05-28 15:41:24.259808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '21238bb1117f'
down_revision: Union[str, None] = '36075c47fab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 先用 product→variety 映射回填 comments.variety_id，再改约束
    op.execute("""
        UPDATE comments c
        SET variety_id = v.id
        FROM products p
        JOIN varieties v ON p.symbol = v.symbol
        WHERE c.product_id = p.id AND c.variety_id IS NULL
    """)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('variety_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('fk_comments_product_id_products', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_comments_product_id_products', 'products', ['product_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('variety_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
