"""add data_ingestion_runs table

Revision ID: 3945d950ad48
Revises: 7a8e00d86747
Create Date: 2026-05-04 22:40:27.054143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3945d950ad48'
down_revision: Union[str, None] = '7a8e00d86747'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_ingestion_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_name', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=True),
    sa.Column('skipped_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_ingestion_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_ingestion_runs_job_name'), ['job_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_ingestion_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_ingestion_runs_job_name'))

    op.drop_table('data_ingestion_runs')
    # ### end Alembic commands ###
