"""add futures extended data tables

Revision ID: 47441c736275
Revises: 3945d950ad48
Create Date: 2026-05-04 23:33:03.828854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47441c736275'
down_revision: Union[str, None] = '3945d950ad48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fut_holding',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.DateTime(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('broker', sa.String(length=50), nullable=True),
    sa.Column('vol', sa.Integer(), nullable=True),
    sa.Column('vol_chg', sa.Integer(), nullable=True),
    sa.Column('long_hld', sa.Integer(), nullable=True),
    sa.Column('long_chg', sa.Integer(), nullable=True),
    sa.Column('short_hld', sa.Integer(), nullable=True),
    sa.Column('short_chg', sa.Integer(), nullable=True),
    sa.Column('exchange', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fut_index',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts_code', sa.String(length=20), nullable=False),
    sa.Column('trade_date', sa.DateTime(), nullable=False),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('open_price', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('pre_close', sa.Float(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('pct_chg', sa.Float(), nullable=True),
    sa.Column('vol', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ts_code', 'trade_date', name='uix_fut_index')
    )
    op.create_table('fut_price_limits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts_code', sa.String(length=20), nullable=False),
    sa.Column('trade_date', sa.DateTime(), nullable=False),
    sa.Column('up_limit', sa.Float(), nullable=True),
    sa.Column('down_limit', sa.Float(), nullable=True),
    sa.Column('exchange', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ts_code', 'trade_date', name='uix_fut_price_limits')
    )
    op.create_table('fut_settle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts_code', sa.String(length=20), nullable=False),
    sa.Column('trade_date', sa.DateTime(), nullable=False),
    sa.Column('settle', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('trading_fee_rate', sa.Float(), nullable=True),
    sa.Column('trading_fee', sa.Float(), nullable=True),
    sa.Column('delivery_fee', sa.Float(), nullable=True),
    sa.Column('b_hedging_margin_rate', sa.Float(), nullable=True),
    sa.Column('s_hedging_margin_rate', sa.Float(), nullable=True),
    sa.Column('long_margin_rate', sa.Float(), nullable=True),
    sa.Column('short_margin_rate', sa.Float(), nullable=True),
    sa.Column('offset_today_fee', sa.Float(), nullable=True),
    sa.Column('exchange', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ts_code', 'trade_date', name='uix_fut_settle')
    )
    op.create_table('fut_weekly_detail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=True),
    sa.Column('prd', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('vol', sa.Float(), nullable=True),
    sa.Column('vol_yoy', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('amout_yoy', sa.Float(), nullable=True),
    sa.Column('cumvol', sa.Float(), nullable=True),
    sa.Column('cumvol_yoy', sa.Float(), nullable=True),
    sa.Column('cumamt', sa.Float(), nullable=True),
    sa.Column('cumamt_yoy', sa.Float(), nullable=True),
    sa.Column('open_interest', sa.Float(), nullable=True),
    sa.Column('interest_wow', sa.Float(), nullable=True),
    sa.Column('mc_close', sa.Float(), nullable=True),
    sa.Column('close_wow', sa.Float(), nullable=True),
    sa.Column('week', sa.String(length=10), nullable=True),
    sa.Column('week_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fut_wsr',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.DateTime(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('fut_name', sa.String(length=50), nullable=True),
    sa.Column('warehouse', sa.String(length=100), nullable=True),
    sa.Column('wh_id', sa.String(length=20), nullable=True),
    sa.Column('pre_vol', sa.Integer(), nullable=True),
    sa.Column('vol', sa.Integer(), nullable=True),
    sa.Column('vol_chg', sa.Integer(), nullable=True),
    sa.Column('area', sa.String(length=50), nullable=True),
    sa.Column('year', sa.String(length=10), nullable=True),
    sa.Column('grade', sa.String(length=20), nullable=True),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('place', sa.String(length=50), nullable=True),
    sa.Column('pd', sa.Integer(), nullable=True),
    sa.Column('is_ct', sa.String(length=10), nullable=True),
    sa.Column('unit', sa.String(length=10), nullable=True),
    sa.Column('exchange', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fut_daily_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('variety_id', sa.Integer(), nullable=False),
    sa.Column('ts_code', sa.String(length=20), nullable=False),
    sa.Column('trade_date', sa.DateTime(), nullable=False),
    sa.Column('pre_close', sa.Float(), nullable=True),
    sa.Column('pre_settle', sa.Float(), nullable=True),
    sa.Column('open_price', sa.Float(), nullable=True),
    sa.Column('high_price', sa.Float(), nullable=True),
    sa.Column('low_price', sa.Float(), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('settle', sa.Float(), nullable=True),
    sa.Column('change1', sa.Float(), nullable=True),
    sa.Column('change2', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('open_interest', sa.Integer(), nullable=True),
    sa.Column('oi_chg', sa.Integer(), nullable=True),
    sa.Column('period', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['variety_id'], ['varieties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variety_id', 'period', 'trade_date', name='uix_fut_daily')
    )
    with op.batch_alter_table('fut_daily_data', schema=None) as batch_op:
        batch_op.create_index('idx_fut_daily_lookup', ['variety_id', 'period', 'trade_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fut_daily_data', schema=None) as batch_op:
        batch_op.drop_index('idx_fut_daily_lookup')

    op.drop_table('fut_daily_data')
    op.drop_table('fut_wsr')
    op.drop_table('fut_weekly_detail')
    op.drop_table('fut_settle')
    op.drop_table('fut_price_limits')
    op.drop_table('fut_index')
    op.drop_table('fut_holding')
    # ### end Alembic commands ###
