"""migrate core price fields from float to numeric

Revision ID: 4d8abe1e048a
Revises: ab0716c8e474
Create Date: 2026-05-20 17:45:14.469619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d8abe1e048a'
down_revision: Union[str, None] = 'ab0716c8e474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fut_daily_data', schema=None) as batch_op:
        batch_op.alter_column('pre_close',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('pre_settle',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('open_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('high_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('low_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('close_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('settle',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('change1',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('change2',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('kline_data', schema=None) as batch_op:
        batch_op.alter_column('open_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=False)
        batch_op.alter_column('high_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=False)
        batch_op.alter_column('low_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=False)
        batch_op.alter_column('close_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('current_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=False)
        batch_op.alter_column('change_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('open_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('high',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('low',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('volume',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)

    with op.batch_alter_table('realtime_quotes', schema=None) as batch_op:
        batch_op.alter_column('current_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=False)
        batch_op.alter_column('change_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('open_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('high',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('low',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('bid1',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('ask1',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('realtime_quotes', schema=None) as batch_op:
        batch_op.alter_column('ask1',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('bid1',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('low',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('high',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('open_price',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('change_percent',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('current_price',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('volume',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('low',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('high',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('open_price',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('change_percent',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('current_price',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    with op.batch_alter_table('kline_data', schema=None) as batch_op:
        batch_op.alter_column('close_price',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.alter_column('low_price',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.alter_column('high_price',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.alter_column('open_price',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    with op.batch_alter_table('fut_daily_data', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('change2',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('change1',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('settle',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('close_price',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('low_price',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('high_price',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('open_price',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('pre_settle',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('pre_close',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    # ### end Alembic commands ###
