"""add_varieties_realtime_kline_watchlists_opinions

Revision ID: 7a8e00d86747
Revises: 
Create Date: 2026-05-02 22:40:49.004806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a8e00d86747'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('varieties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('contract_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('contract_month', sa.String(length=10), nullable=True),
    sa.Column('tick_size', sa.Float(), nullable=True),
    sa.Column('multiplier', sa.Float(), nullable=True),
    sa.Column('margin_rate', sa.Float(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('listing_date', sa.DateTime(), nullable=True),
    sa.Column('last_trading_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_code')
    )
    op.create_index(op.f('ix_varieties_category'), 'varieties', ['category'], unique=False)
    op.create_index(op.f('ix_varieties_symbol'), 'varieties', ['symbol'], unique=True)
    op.create_table('kline_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('variety_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('trading_time', sa.DateTime(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('open_interest', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['variety_id'], ['varieties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variety_id', 'period', 'trading_time', name='uix_kline')
    )
    op.create_index('idx_kline_lookup', 'kline_data', ['variety_id', 'period', 'trading_time'], unique=False)
    op.create_table('opinions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('variety_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['variety_id'], ['varieties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('realtime_quotes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('variety_id', sa.Integer(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('change_percent', sa.Float(), nullable=True),
    sa.Column('open_price', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('open_interest', sa.Integer(), nullable=True),
    sa.Column('bid1', sa.Float(), nullable=True),
    sa.Column('ask1', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['variety_id'], ['varieties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variety_id')
    )
    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('variety_id', sa.Integer(), nullable=False),
    sa.Column('resistance_level', sa.Float(), nullable=True),
    sa.Column('support_level', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_notified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['variety_id'], ['varieties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlists')
    op.drop_table('realtime_quotes')
    op.drop_table('opinions')
    op.drop_index('idx_kline_lookup', table_name='kline_data')
    op.drop_table('kline_data')
    op.drop_index(op.f('ix_varieties_symbol'), table_name='varieties')
    op.drop_index(op.f('ix_varieties_category'), table_name='varieties')
    op.drop_table('varieties')
    # ### end Alembic commands ###
