"""add_fut_contracts_table

Revision ID: aa66a16f977d
Revises: ff017239116d
Create Date: 2026-05-06 21:22:47.854987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa66a16f977d'
down_revision: Union[str, None] = 'ff017239116d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fut_contracts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts_code', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('fut_code', sa.String(length=10), nullable=True),
    sa.Column('exchange', sa.String(length=10), nullable=True),
    sa.Column('list_date', sa.DateTime(), nullable=True),
    sa.Column('delist_date', sa.DateTime(), nullable=True),
    sa.Column('multiplier', sa.Float(), nullable=True),
    sa.Column('trade_unit', sa.String(length=20), nullable=True),
    sa.Column('per_unit', sa.Float(), nullable=True),
    sa.Column('quote_unit', sa.String(length=20), nullable=True),
    sa.Column('d_month', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ts_code', name='uix_fut_contracts_ts_code')
    )
    with op.batch_alter_table('fut_contracts', schema=None) as batch_op:
        batch_op.create_index('idx_fut_contracts_lookup', ['fut_code', 'exchange', 'list_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fut_contracts_delist_date'), ['delist_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fut_contracts_exchange'), ['exchange'], unique=False)
        batch_op.create_index(batch_op.f('ix_fut_contracts_fut_code'), ['fut_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_fut_contracts_list_date'), ['list_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fut_contracts_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_fut_contracts_ts_code'), ['ts_code'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fut_contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fut_contracts_ts_code'))
        batch_op.drop_index(batch_op.f('ix_fut_contracts_symbol'))
        batch_op.drop_index(batch_op.f('ix_fut_contracts_list_date'))
        batch_op.drop_index(batch_op.f('ix_fut_contracts_fut_code'))
        batch_op.drop_index(batch_op.f('ix_fut_contracts_exchange'))
        batch_op.drop_index(batch_op.f('ix_fut_contracts_delist_date'))
        batch_op.drop_index('idx_fut_contracts_lookup')

    op.drop_table('fut_contracts')
    # ### end Alembic commands ###
