"""add_unique_constraints_for_fut_wsr_holding_weekly

Revision ID: ff017239116d
Revises: 8027809b23b3
Create Date: 2026-05-06 15:01:33.914707

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ff017239116d'
down_revision: str | None = '8027809b23b3'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fut_holding', schema=None) as batch_op:
        batch_op.create_index('idx_fut_holding_lookup', ['trade_date', 'symbol', 'broker'], unique=False)
        batch_op.create_unique_constraint('uix_fut_holding', ['trade_date', 'symbol', 'broker'])

    # fut_price_limits.name/m_ratio/cont are owned by a3af320d7bcd.
    # Do not re-inspect or re-add them here during a clean PostgreSQL upgrade.
    with op.batch_alter_table('fut_weekly_detail', schema=None) as batch_op:
        batch_op.create_index('idx_fut_weekly_lookup', ['week', 'prd', 'exchange'], unique=False)
        batch_op.create_unique_constraint('uix_fut_weekly_detail', ['week', 'prd', 'exchange'])

    with op.batch_alter_table('fut_wsr', schema=None) as batch_op:
        batch_op.create_index('idx_fut_wsr_lookup', ['trade_date', 'symbol', 'warehouse'], unique=False)
        batch_op.create_unique_constraint('uix_fut_wsr', ['trade_date', 'symbol', 'warehouse', 'wh_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fut_wsr', schema=None) as batch_op:
        batch_op.drop_constraint('uix_fut_wsr', type_='unique')
        batch_op.drop_index('idx_fut_wsr_lookup')

    with op.batch_alter_table('fut_weekly_detail', schema=None) as batch_op:
        batch_op.drop_constraint('uix_fut_weekly_detail', type_='unique')
        batch_op.drop_index('idx_fut_weekly_lookup')

    with op.batch_alter_table('fut_holding', schema=None) as batch_op:
        batch_op.drop_constraint('uix_fut_holding', type_='unique')
        batch_op.drop_index('idx_fut_holding_lookup')

    # ### end Alembic commands ###
